name: test the workflow
on: push
jobs:
  Container-image-1:
    runs-on: windows-latest
    container: node:19-alpine3.16
    steps:
      - name: Run the Container
        run: |
          node --version
          npm --version

  
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Repo
        uses: actions/checkout@v3
        
      - name: Install Required Python Version
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          
      - name:  Install Dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install pytest
          
      - name: test the Script
        run: |
          export PYTHONPATH=src
          pytest

